# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


# report: "report/workflow.rst"

# # Allow users to fix the underlying OS via singularity.
# singularity: "docker://continuumio/miniconda3"

include: "rules/common.smk"
include: "rules/other.smk"


rule all:
    input:
        all_input