rule tests:
    message: "Running unit tests..."
    conda: "../workflow/rules/envs/smf_py3_v7.yaml"
    shell:
        r"""
        PYTHONPATH=workflow/scripts \
        python -m unittest discover -s tests -v
        """