# Run tests with `snakemake --cores 1 --use-conda tests` in the tests directory

rule tests:
    message: "Running unit tests..."
    conda: "../workflow/rules/envs/smf_py3_v7.yaml"
    shell:
        r"""
        PYTHONPATH=../workflow/scripts \
        python -m unittest discover -s . -v
        """